name: savings_bank_minimum_balance_analyzer_dart
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.3.0-214.0.dev <4.0.0'

dependencies:
  grizzly_io:
    git: https://github.com/Baneeishaque/grizzly_io.git
  intl: ^0.18.0
  jiffy: ^6.2.1
  tuple: ^2.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
