name: savings_bank_minimum_balance_resolver_common
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.1.0-15.0.dev <4.0.0'

dependencies:
  grizzly_io:
    git: https://github.com/Baneeishaque/grizzly_io.git
  intl: ^0.18.0
  dart_date:
    git: https://github.com/spaznuski/dart_date.git
  sugar: ^2.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
