name: savings_bank_minimum_balance_analyzer_dart
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  grizzly_io:
    git: https://github.com/Grizzly-dart/grizzly_io.git
  jiffy: 6.2.1
  tuple: 2.0.2
